### ISSUE TITLE
CADENCE

### ISSUE THREAD

**Issue by xuxumatu** [sk-/estimated_power#1]
Hi i´m developing a similar app so i want to know it this string is for not to calculate power if cadence is zero thanks a lot you can help me a lot

        if (cadence == null) {
    		cadence = 90;
//    	} else if (cadence < 10) {
//    		return 0;
    	}

**Comment by sk-** [comment]
What the code is doing is assigning a default cadence of 90 if there's no cadence data.

In your case what you want to do is to return `null` in case the cadence is `null` and then handle that to render the power as `---`.

**Comment by xuxumatu** [comment]
thanks a lot
